# Generated by Django 3.0.5 on 2020-04-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menuitem_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, default='restaurant_no_image.png', upload_to='restaurant_pictures'),
        ),
    ]
