# Generated by Django 3.0.5 on 2020-04-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20200420_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='role',
            field=models.CharField(default='restaurant', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='food_no_image.jpg', upload_to='food_pictures/'),
        ),
    ]
