# Generated by Django 3.0.5 on 2020-04-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20200420_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='speciality',
            field=models.BooleanField(default=False),
        ),
    ]
